name: docker-image

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2.4.0
      with:
        context: .
        build-args: |
          VERSION=${{ matrix.version }}
        tags: ${{ matrix.version }}
        push: ${{ github.event_name != 'pull_request' }}
